### ISSUE TITLE
Does not work with interpolation

### ISSUE THREAD

**Issue by zaikin-andrew** [NetanelBasal/angular2-shave#1]
Hi @NetanelBasal !
Thanks for the directive! It works great with a static text but not with any interpolation. 
`{{'lorem ipsum'}}` looks like a `''` empty string for this directive. 

Could you fix it or give an advice how to manage it with another pipe? 
The main reason to use this directive is truncate text by height of the element.

**Comment by NetanelBasal** [comment]
I will check it and let you know.

**Comment by NetanelBasal** [comment]
Fixed in 1.1.0.
